In [21]:
from sklearn import*
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score



In [22]:
df=pd.read_csv('hire_data1.csv')
df

Percentage  Backlog  Internship  First_Round  Communication_Skills  \
0         81.00        0           1        75.00                 80.00   
1         70.00        0           3        87.00                 70.00   
2         81.00        2           3        75.00                 67.00   
3         56.00        3           3        42.00                 76.00   
4         74.00        4           3        82.00                 75.00   
..          ...      ...         ...          ...                   ...   
372       68.87        2           0        66.67                 69.69   
373       80.48        0           3        79.00                 88.89   
374       65.00        2           1        60.00                 70.00   
375      100.00        5           3        88.00                 88.00   
376      100.00        8           1        88.00                 88.00   

     Hired   Name  
0        1  Canon  
1        1   Ajay  
2        0   Aman  
3        0   Amir  
4        1   Monu  
..     ...    ...  
372      0   Ajay  
373      1    Zar  
374      1   Teja  
375      1   Monu  
376      0   Baba  

[377 rows x 7 columns]

In [23]:
features=df.columns[:5]
features

Index(['Percentage', 'Backlog', 'Internship', 'First_Round',
       'Communication_Skills'],
      dtype='object')

In [24]:
x=df[features]
x

Percentage  Backlog  Internship  First_Round  Communication_Skills
0         81.00        0           1        75.00                 80.00
1         70.00        0           3        87.00                 70.00
2         81.00        2           3        75.00                 67.00
3         56.00        3           3        42.00                 76.00
4         74.00        4           3        82.00                 75.00
..          ...      ...         ...          ...                   ...
372       68.87        2           0        66.67                 69.69
373       80.48        0           3        79.00                 88.89
374       65.00        2           1        60.00                 70.00
375      100.00        5           3        88.00                 88.00
376      100.00        8           1        88.00                 88.00

[377 rows x 5 columns]

In [25]:
y=df[['Hired']]
y

Hired
0        1
1        1
2        0
3        0
4        1
..     ...
372      0
373      1
374      1
375      1
376      0

[377 rows x 1 columns]

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)


In [32]:
from sklearn.linear_model import LogisticRegression

In [35]:
lr=LogisticRegression()

In [38]:
abc=lr.fit(x_train,y_train)


C:\Users\MADHAV SHARMA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [39]:
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1], dtype=int64)

In [13]:
print(metrics.accuracy_score(y_test,y_pred)*100)


86.8421052631579


In [41]:
y_pred=lr.predict(x_test)
a=np.ravel(y_pred)
a
           
           

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1], dtype=int64)

In [42]:
lm=np.array([80,0,1,70,60],dtype='float').reshape(1,-1)
print(lm)

[[80.  0.  1. 70. 60.]]
